theme: jekyll-theme-minimal
title: Samuel Albanese
markdown: kramdown
logo: assets/img/bob.jpg
author: Sam Albanese
description: 
  Undergraduate studying Computer Science at St Marys College of Maryland <br/>
  Focus in Software Development<br/>
  <a class="fab fa-envelope-square fa-2x" href="mailto:samuelpalbanese@gmail.com"></a> | <a class="fab fa-linkedin-square fa-2x" href="https://www.linkedin.com/in/spalby/"></a> | <a class="fab fa-instagram-square fa-2x" href="https://www.instagram.com/samapplebees/"></a> <a class="fab fa-github-square fa-2x" href="https://www.github.com/spalby/"></a>
